baseURL = 'https://example.org/'
languageCode = 'en-us'

[params]
displayName = 'Li Bai'
displayNameAlter = '李白'


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30



[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"